pipeline {
    agent any
    stages {
        stage('Pull code') {
            steps {
               git branch: 'dev', url: 'https://github.com/SilverSky9/DevToolNo1.git'
            }
        }
         stage('Download dependencies') {
            steps {
                dir("frontend") {
                sh "pwd"
                sh 'ls'
                sh 'npm install'
                }
            }
        }
        stage('Unit test'){
            steps{
                dir("frontend"){
                      script {
                        if (!fileExists('reports')) {
                            sh 'mkdir reports'
                        }
                    }
                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'reports', reportFiles: 'unit.txt', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                  
                }
            }
        }
        stage('Component test'){
            steps{
                dir("frontend"){
                      script {
                        if (!fileExists('reports')) {
                            sh 'mkdir reports'
                        }
                    }
                        sh 'npm run test 2> reports/component.txt'
                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'reports', reportFiles: 'component.txt', reportName: 'Component Test Report', reportTitles: 'Component Test Report'])
                  
                }
            }
        }
        // stage('Component test') {
        //     steps {
        //         echo 'Skip'
        //         // sh 'cd frontend'
        //         //  sh 'pwd'
        //         // sh 'cd /var/lib/jenkins/workspace/team-10-frontend/frontend'
        //         // sh 'ls'
        //         // sh 'apt-get install xvfb'
        //          dir("frontend") {
        //         sh 'npx cypress run --record --spec cypress/integration/component-test_spec.js'
        //          }
        //     }
        // }
        stage('Deploy') {
            steps {
                echo 'Test'
            }
        }
    }
}
