version: "3"
services:
  app:
    build: ./backend
    container_name: go_container
    volumes:
    - './backend:/app'
    working_dir: /app
    env_file:
      - db.env
    ports:
    - 3000:3000
    # command: go run main.go
    depends_on:
      - db
    networks:
      - fullstack
  db:
    image: postgres
    container_name: postgres_container
    env_file:
      - db.env
    ports:
    - 5432:5432
    volumes:
      - ./db/:/var/lib/postgresql/data/
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - fullstack
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped
  web:
    build: ./frontend
    image: silversky9/team-10-frontend:1.0
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - app
    # volumes:
    # - ./out:/usr/share/nginx/html
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
