version: "3"
services:
  app:
    image: silversky9/team-10-backend:1.0.251
    build: ./backend
    container_name: team10_go_container
  web:
    build: ./frontend
    image: silversky9/team-10-frontend:1.0.114
    container_name: team10_nginx_container