version: '2.0'
services:
  web:
      image: nginx:1.21.6-alpine
      container_name: worker-nginx
      ports:
      - "80:80"
      volumes:
      - ../html/:/usr/share/nginx/html
  app:
    image: golang:1.16-alpine
    container_name: microservices
    volumes:
      - './:/app'
    working_dir: /app
    ports:
      - 8181:8181
    command: go run main.go