version: '2.0'
services:
  web:
      image: nginx:1.21.6-alpine
      container_name: worker-nginx
      ports:
      - "80:80"
      volumes:
      - ../html/:/usr/share/nginx/html
      links:
      - app
  app:
    build:
      context: .
      dockerfile: .
    container_name: worker-go
    volumes:
    - '../backend:/app'
    working_dir: /app
    ports:
    - 3000:3000
    command: go run main.go
    links:
    - db
  db:
    image: postgres
    container_name: worker-db
    env_file:
      - db.env
    ports:
    - 5432:5432
    volumes:
      - ../db:/var/lib/postgresql/data/
