version: '2.0'
services:
  web:
      image: nginx:1.21.6-alpine
      container_name: worker-nginx
      ports:
      - "80:80"
      volumes:
      - ../html/:/usr/share/nginx/html
  app:
    build:
      context: .
      dockerfile: .
    container_name: worker-go
    volumes:
    - '../go/:/app'
    working_dir: /app
    ports:
    - 8181:8181
    command: go run main.go